### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by miaadev** [julienduroure/extension_collection#1]
`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\io\exp\gltf2_io_user_extensions.py", line 14, in export_user_extensions
    hook(*args, export_settings)
  File "C:\Users\wiene\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\gltf_collection_export.py", line 111, in gather_node_hook
    extension={"collections": [c.name for c in blender_object.users_collection]},
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Collection' object has no attribute 'users_collection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\io\exp\gltf2_io_user_extensions.py", line 16, in export_user_extensions
    export_settings['log'].error("Extension hook " + hook_name + " fails on " + extension)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "glTF2ExportUserExtension") to str
`

**Comment by julienduroure** [comment]
About the second problem: This is already solved on 4.2.2

About the main issue: 
This hook is no more relevant, as this feature is now directly included with glTF-Blender-IO.

![image](https://github.com/user-attachments/assets/454b88b7-e8f4-44aa-9c5d-c625d8831409)


Closing this ticket.
If you have some issue with the official addon, please report it here (with a test file) : https://github.com/KhronosGroup/glTF-Blender-IO/issues
